### ISSUE TITLE
Кикать молчунов на входе

### ISSUE THREAD

**Issue by girokon** [emilkip/devkz-bot#1]
Если кто-то вошел в чат, и в течении часа ничего не написал, то кикнуть его из чата

**Comment by emilkip** [comment]
Да пусть сидят. Никого не трогают. Бывает кстати интересно просто со стороны почитать, не участвуя в беседах. Аля бложек из многих авторов. В будущем может заинтересуются и вольются в беседы.

**Comment by girokon** [comment]
Есть в этом смысл, кикать наверное слишком радикально

**Comment by shadowsmind** [comment]
Думаю просто стоит в том же дисклеймере предложить человеку представиться и т.д.

**Comment by emilkip** [comment]
Подобное можно добавить.

**Comment by girokon** [comment]
Не в дисклеймере, а в приветственном меседже тогда, я подозреваю дисклеймер далеко не сразу идут читать

**Comment by emilkip** [comment]
Да, есть такое. Ну тогда в приветствие это будет разумнее написать.
